version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arkemis-app
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/var/www/html:rw,cached
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:11.4
    container_name: arkemis-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p$${MARIADB_ROOT_PASSWORD} || exit 1"]
      interval: 5s
      timeout: 5s
      start_period: 20s
      retries: 30
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
