services:
  # Expose le port MariaDB sur l'hôte (optionnel, utile pour un client SQL local)
  db:
    ports:
      - "3306:3306"

  # Mailpit (facultatif) pour capturer les emails envoyés par l'app en dev
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
